version: '3'

services:
  filesdb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - files_data:/data/db
      - ./database/mongo.yml:/etc/mongo/mongo.yml
    entrypoint: ["mongod", "--config", "/etc/mongo/mongo.yml", "--bind_ip", "localhost, filesdb"]

  fileservice:
    env_file:
      - ./fileservice/.env
    image: alpine
    volumes:
      - ./fileservice/build:/app
    command:
      - "/app/fileservice"
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    build: database/
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - database/.env
    ports:
      - 3307:3306
  
  node:
    depends_on:
      - db
    build: backend/
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/views:/server/views

  nginx:
    build: nginx/
    depends_on:
      - node
    ports:
      - 80:80
    volumes:
      - ./backend/static:/site

volumes:
  db_data:
  files_data: