FROM node:lts-slim
WORKDIR /server
ADD ./package.json /server/
RUN npm install
ADD ./src /server/src
ADD ./config.json /server/
ADD ./tsconfig.json /server/
RUN npx tsc
EXPOSE 80
CMD [ "node", "dist/index.js" ]